name: Fetch Weather Data

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'

    - name: Restore dependencies
  run: dotnet restore backend/backend.fsproj


      - name: Fetch weather data
        run: dotnet fsi backend/weather_service.fsx

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add weather_data.json
          git commit -m "Auto-updated weather data for Andover, KS"
          git push
