name: Fetch Weather Data

on:
  schedule:
    - cron: "0 6 * * *"  # Runs daily at 6 AM UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  fetch-weather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0'  # Ensure the correct .NET version is installed

      - name: Verify .NET installation
        run: dotnet --info  # Debugging step to check if .NET is installed

      - name: Restore dependencies
        run: |
          cd backend
          ls -al  # Debugging: Show files in backend/
          dotnet restore backend.fsproj

      - name: Fetch weather data
        run: |
          cd backend
          dotnet run --project backend.fsproj

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add weather_data.json
          git commit -m "Auto-updated weather data for Andover, KS"
          git push

